var json__1 = {
"type": "FeatureCollection",
"name": "_1",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=5426\"><img src=\"http:\/\/www.temples.ru\/private\/f000657\/657_0119213g.jpg\" border=1 width=\"180\" height=\"137\"><\/a><br><br>\nЯрославская обл., г. Переславль-Зал�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 38.852671, 56.735608, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского при земской больнице (не сохр.)", "descriptio": "\n<div align=\"center\">г. Ярославль, ул. Загородный Сад, [11, перед главным корпусом]<br><br><a href=\"http:\/\/www.temples.ru\/card.php?ID=4190\"><nobr><i>Подробная информация<\/i><\/nobr><\/a><br><b", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 39.8648, 57.639626, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=4160\"><img src=\"http:\/\/www.temples.ru\/private\/f000019\/019_0000530g.jpg\" border=1 width=\"128\" height=\"180\"><\/a><br><br>\nг. Ярославль, ул. Андропова, 8<br><br><a hr", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 39.890954, 57.625504, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Демидовском лицее (не сохр.)", "descriptio": "\n<div align=\"center\">г. Ярославль, [пл. Челюскинцев]<br><br><a href=\"http:\/\/www.temples.ru\/card.php?ID=4139\"><nobr><i>Подробная информация<\/i><\/nobr><\/a><br><br><\/div>", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 39.902633, 57.622087, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Любиме (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=17218\"><img src=\"http:\/\/www.temples.ru\/private\/f000399\/399_0114913g.jpg\" border=1 width=\"180\" height=\"180\"><\/a><br><br>\nЯрославская обл., Любимский р-н, г. �", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 40.68445, 58.36233, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского - памятник защитникам Отечества во все времена (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=6321\"><img src=\"http:\/\/www.temples.ru\/private\/f000029\/2007-06-16_4286065g.jpg\" border=1 width=\"180\" height=\"121\"><\/a><br><br>\nЯрославская обл., г. Углич, Успе�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 38.318967, 57.526777, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Заозерье (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=15353\"><img src=\"http:\/\/www.temples.ru\/private\/f000306\/306_0044535g.jpg\" border=1 width=\"118\" height=\"180\"><\/a><br><br>\nЯрославская обл., Угличский р-н. с. �", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 38.244873, 57.197031, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Макарово (действ.)", "descriptio": "\n<div align=\"center\">Ярославская обл., Рыбинский р-н, с. Макарово<br><br><a href=\"http:\/\/www.temples.ru\/card.php?ID=3385\"><nobr><i>Подробная информация<\/i><\/nobr><\/a><br><br><\/div>", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 38.722276, 58.076892, 0.0 ] } }
]
}
