var json__10 = {
"type": "FeatureCollection",
"name": "_10",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского (кладбищенская) в Соколино (не сохр.)", "descriptio": "\n<div align=\"center\">Смоленская обл., Сычевский р-н, д. Соколино<br><br><a href=\"http:\/\/www.temples.ru\/card.php?ID=16397\"><nobr><i>Подробная информация<\/i><\/nobr><\/a><br><br><\/div>", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 34.415903, 55.851228, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Вязьме-Брянской (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=16887\"><img src=\"http:\/\/www.temples.ru\/private\/f000306\/306_0108854g.jpg\" border=1 width=\"180\" height=\"177\"><\/a><br><br>\nСмоленская обл., Вяземский р-н, с. В�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 34.343407, 55.167796, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Вонлярово (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=10043\"><img src=\"http:\/\/www.temples.ru\/private\/f000101\/108_0020954g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nСмоленская обл., Смоленский р-н, д. �", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 31.64017, 54.76982, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского при Мужской гимназии (не сохр.)", "descriptio": "\n<div align=\"center\">Смоленская обл., Вяземский р-н, г. Вязьма, [угол ул. Просвещения и ул. Покровского]<br><br><a href=\"http:\/\/www.temples.ru\/card.php?ID=10066\"><nobr><i>Подробная и", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 34.299311, 55.207829, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Спасо-Преображенском Рославльском монастыре (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=10104\"><img src=\"http:\/\/www.temples.ru\/private\/f000306\/306_0021278g.jpg\" border=1 width=\"119\" height=\"180\"><\/a><br><br>\nСмоленская обл., Рославльский р-н, �", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 32.86245, 53.9516, 0.0 ] } }
]
}
