var json__11 = {
"type": "FeatureCollection",
"name": "_11",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского на Гальянке (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=10358\"><img src=\"http:\/\/www.temples.ru\/private\/f000295\/295_0023498g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nСвердловская обл., г. Нижний Тагил,", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 59.969881, 57.891748, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского при церкви Сошествия Святого Духа (не сохр.)", "descriptio": "\n<div align=\"center\">г. Екатеринбург, ул. Малышева, [44]<br><br><a href=\"http:\/\/www.temples.ru\/card.php?ID=11663\"><nobr><i>Подробная информация<\/i><\/nobr><\/a><br><br><\/div>", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 60.600554, 56.833961, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Собор Александра Невского в Ново-Тихвинском монастыре (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=11621\"><img src=\"http:\/\/www.temples.ru\/private\/f000002\/002_0058151g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nг. Екатеринбург, ул. Зеленая Роща, 1<", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 60.598729, 56.822893, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского на Хлебной площади (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=11631\"><img src=\"http:\/\/www.temples.ru\/private\/f000002\/002_0058060g.jpg\" border=1 width=\"180\" height=\"134\"><\/a><br><br>\nг. Екатеринбург, ул. 8-го Марта, денд", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 60.602864, 56.828742, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Нижней Салде (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=20512\"><img src=\"http:\/\/www.temples.ru\/private\/f000295\/295_0163619g.jpg\" border=1 width=\"119\" height=\"180\"><\/a><br><br>\nСвердловская обл., г. Нижняя Салда,", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 60.70773, 58.076602, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского (не сохр.)", "descriptio": "\n<div align=\"center\">г. Екатеринбург, ул. Свердлова, [11A]<br><br><a href=\"http:\/\/www.temples.ru\/card.php?ID=11630\"><nobr><i>Подробная информация<\/i><\/nobr><\/a><br><br><\/div>", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 60.603915, 56.850566, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Каменске-Уральском (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=9001\"><img src=\"http:\/\/www.temples.ru\/private\/f000295\/295_0014320g.jpg\" border=1 width=\"135\" height=\"180\"><\/a><br><br>\nСвердловская обл., г. Каменск-Ураль�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 61.917402, 56.414212, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского при Алексеевском реальном училище (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=11629\"><img src=\"http:\/\/www.temples.ru\/private\/f000002\/002_0058086g.jpg\" border=1 width=\"135\" height=\"180\"><\/a><br><br>\nг. Екатеринбург, просп. Ленина, 13<br><", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 60.588832, 56.837165, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Красноуфимске (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=11831\"><img src=\"http:\/\/www.temples.ru\/private\/f000002\/002_0046397g.jpg\" border=1 width=\"154\" height=\"180\"><\/a><br><br>\nСвердловская обл., г. Красноуфимск,", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 57.773092, 56.616219, 0.0 ] } }
]
}
