var json__17 = {
"type": "FeatureCollection",
"name": "_17",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Азино (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=20174\"><img src=\"http:\/\/www.temples.ru\/private\/f000656\/656_0158946g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nг. Казань, ул. Академика Сахарова, 16", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 49.228621, 55.782026, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского при Александровской больнице (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=16898\"><img src=\"http:\/\/www.temples.ru\/private\/f000630\/630_0108990g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nРеспублика Татарстан, г. Казань, ул", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 49.134679, 55.789628, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Елабуге (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=13318\"><img src=\"http:\/\/www.temples.ru\/private\/f000002\/002_0062676g.jpg\" border=1 width=\"119\" height=\"180\"><\/a><br><br>\nресп. Татарстан, г. Елабуга, Набере�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 52.057589, 55.753166, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Никольском (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=16786\"><img src=\"http:\/\/www.temples.ru\/private\/f000630\/630_0132561g.jpg\" border=1 width=\"135\" height=\"180\"><\/a><br><br>\nресп. Татарстан, Лаишевский р-н, с. �", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 49.190372, 55.534745, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского на Раифском подворье (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=12585\"><img src=\"http:\/\/www.temples.ru\/private\/f000130\/130_0081700g.jpg\" border=1 width=\"121\" height=\"180\"><\/a><br><br>\nг. Казань, ул. Московская, 39<br><br><a href", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 49.109005, 55.788175, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Юдино (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=6180\"><img src=\"http:\/\/www.temples.ru\/private\/f000043\/047_0003241g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nРеспублика Татарстан, г. Казань, пг�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 48.878337, 55.817943, 0.0 ] } }
]
}
