var json__19 = {
"type": "FeatureCollection",
"name": "_19",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Лесном Ардашево (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=17693\"><img src=\"http:\/\/www.temples.ru\/private\/f000541\/541_0120629g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nресп. Мордовия, Темниковский р-н, с.", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 43.132335, 54.583258, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского при паломническом центре Иоанно-Богословского Макаровского монастыря (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=17755\"><img src=\"http:\/\/www.temples.ru\/private\/f000687\/687_0126550g.jpg\" border=1 width=\"180\" height=\"120\"><\/a><br><br>\nресп. Мордовия, г. Саранск, с. Макар�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 45.255228, 54.161573, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Александровке (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=19316\"><img src=\"http:\/\/www.temples.ru\/private\/f000687\/687_0143330g.jpg\" border=1 width=\"180\" height=\"163\"><\/a><br><br>\nресп. Мордовия, Лямбирский р-н, с. А�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 45.254268, 54.272107, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Озерном (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=17894\"><img src=\"http:\/\/www.temples.ru\/private\/f000687\/687_0127164g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nРеспублика Мордовия, г. Саранск, по", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 45.288271, 54.229892, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=16602\"><img src=\"http:\/\/www.temples.ru\/private\/f000541\/541_0103328g.jpg\" border=1 width=\"135\" height=\"180\"><\/a><br><br>\nресп. Мордовия, г. Саранск, пл. Побе�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 45.18221, 54.180741, 0.0 ] } }
]
}
