var json__23 = {
"type": "FeatureCollection",
"name": "_23",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Великих Луках (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=15119\"><img src=\"http:\/\/www.temples.ru\/private\/f000360\/360_0083033g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nПсковская обл., г. Великие Луки, пл.", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 30.514768, 56.344644, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Сосновом Бору (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=18069\"><img src=\"http:\/\/www.temples.ru\/private\/f000093\/100_0128392g.jpg\" border=1 width=\"180\" height=\"134\"><\/a><br><br>\nПсковская обл., Себежский р-н, пос. �", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 28.327481, 56.254789, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского при 76-й десантно-штурмовой Черниговской дивизии (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=9560\"><img src=\"http:\/\/www.temples.ru\/private\/f000242\/242_0133637g.jpg\" border=1 width=\"180\" height=\"178\"><\/a><br><br>\nг. Псков, ул. Мирная, 1<br><br><a href=\"http:\/\/www", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 28.32167, 57.807906, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского у Жидилова Бора (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=19600\"><img src=\"http:\/\/www.temples.ru\/private\/f000651\/651_0147620g.jpg\" border=1 width=\"135\" height=\"180\"><\/a><br><br>\nПсковская обл., Псковский р-н, 1 км Ю", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 28.219242, 57.918788, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Печорах (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=12697\"><img src=\"http:\/\/www.temples.ru\/private\/f000264\/264_0056867g.jpg\" border=1 width=\"135\" height=\"180\"><\/a><br><br>\nПсковская обл., Печорский р-н, г. Пе�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 27.614329, 57.812006, 0.0 ] } }
]
}
