var json__24 = {
"type": "FeatureCollection",
"name": "_24",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Савино (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=10824\"><img src=\"http:\/\/www.temples.ru\/private\/f000274\/274_0029939g.jpg\" border=1 width=\"180\" height=\"134\"><\/a><br><br>\nПермский край, Карагайский р-н, д. С", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 54.985422, 58.187033, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Усть-Качке (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=8941\"><img src=\"http:\/\/www.temples.ru\/private\/f000274\/274_0013333g.jpg\" border=1 width=\"180\" height=\"106\"><\/a><br><br>\nПермский край, Пермский р-н, с. Усть-", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 55.66044, 58.001037, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Быме (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=7632\"><img src=\"http:\/\/www.temples.ru\/private\/f000274\/274_0106839g.jpg\" border=1 width=\"180\" height=\"131\"><\/a><br><br>\nПермский край, Кунгурский р-н, с. Бы�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 56.327779, 57.435194, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Мысах (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=8790\"><img src=\"http:\/\/www.temples.ru\/private\/f000274\/274_0012038g.jpg\" border=1 width=\"180\" height=\"133\"><\/a><br><br>\nПермский край, Краснокамский р-н, д.", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 55.911579, 58.060853, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Лобаново (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=8650\"><img src=\"http:\/\/www.temples.ru\/private\/f000274\/274_0011134g.jpg\" border=1 width=\"180\" height=\"120\"><\/a><br><br>\nПермский край, Пермский р-н, с. Лоба�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 56.300889, 57.860972, 0.0 ] } }
]
}
