var json__26 = {
"type": "FeatureCollection",
"name": "_26",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Ливнах (не сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=20294\"><img src=\"http:\/\/www.temples.ru\/private\/f000794\/794_0162333g.jpg\" border=1 width=\"180\" height=\"128\"><\/a><br><br>\nОрловская обл., г. Ливны, пл. Сергия", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 37.607308, 52.419012, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского при Александровском реальном училище (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=11386\"><img src=\"http:\/\/www.temples.ru\/private\/f000616\/616_0106049g.jpg\" border=1 width=\"120\" height=\"180\"><\/a><br><br>\nг. Орел, ул. Комсомольская, 39<br><br><a hr", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 36.065497, 52.957978, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь-часовня Александра Невского в 909-м квартале (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=11418\"><img src=\"http:\/\/www.temples.ru\/private\/f000002\/002_0041856g.jpg\" border=1 width=\"135\" height=\"180\"><\/a><br><br>\nг. Орел, ул. Машкарина<br><br><a href=\"http:\/\/w", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 36.018622, 52.925342, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского (не сохр.)", "descriptio": "\n<div align=\"center\">г. Орел, [сквер Танкистов]<br><br><a href=\"http:\/\/www.temples.ru\/card.php?ID=11414\"><nobr><i>Подробная информация<\/i><\/nobr><\/a><br><br><\/div>", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 36.076612, 52.967471, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Ливнах (надкладезная) (не сохр.)", "descriptio": "\n<div align=\"center\">Орловская обл., г. Ливны<br><br><a href=\"http:\/\/www.temples.ru\/card.php?ID=20295\"><nobr><i>Подробная информация<\/i><\/nobr><\/a><br><br><\/div>", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 37.60791, 52.418361, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского при Орловской мужской гимназии (не сохр.)", "descriptio": "\n<div align=\"center\">г. Орел, Воскресенский пер., 5<br><br><a href=\"http:\/\/www.temples.ru\/card.php?ID=11385\"><nobr><i>Подробная информация<\/i><\/nobr><\/a><br><br><\/div>", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 36.066914, 52.96247, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Успенском Орловском монастыре (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=11364\"><img src=\"http:\/\/www.temples.ru\/private\/f000264\/264_0103510g.jpg\" border=1 width=\"136\" height=\"180\"><\/a><br><br>\nг. Орел, ул. Ермолова, 13А<br><br><a href=\"http", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 36.077612, 52.977535, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Ливнах (сохр.)", "descriptio": "\n<div align=\"center\">Орловская обл., г. Ливны, объездная дорога<br><br><a href=\"http:\/\/www.temples.ru\/card.php?ID=20306\"><nobr><i>Подробная информация<\/i><\/nobr><\/a><br><br><\/div>", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 37.649119, 52.427376, 0.0 ] } }
]
}
