var json__29 = {
"type": "FeatureCollection",
"name": "_29",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Часовня Царственных Страстотерпцев в Покровском Александро-Невском Колыванском монастыре (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=8281\"><img src=\"http:\/\/www.temples.ru\/private\/f000225\/225_0009490g.jpg\" border=1 width=\"147\" height=\"180\"><\/a><br><br>\nНовосибирская обл., Колыванский р-н", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 82.732447, 55.299728, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Покровском Александро-Невском Колыванском монастыре (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=8280\"><img src=\"http:\/\/www.temples.ru\/private\/f000225\/225_0009484g.jpg\" border=1 width=\"180\" height=\"157\"><\/a><br><br>\nНовосибирская обл., Колыванский р-н", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 82.73278, 55.299563, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня надкладезная при соборе Александра Невского (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=8031\"><img src=\"http:\/\/www.temples.ru\/private\/f000225\/225_0009425g.jpg\" border=1 width=\"120\" height=\"180\"><\/a><br><br>\nг. Новосибирск, ул. Советская, 1А<br><br", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 82.922605, 55.019169, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Иоанна Предтечи при соборе Александра Невского (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=8030\"><img src=\"http:\/\/www.temples.ru\/private\/f000563\/563_0112227g.jpg\" border=1 width=\"180\" height=\"127\"><\/a><br><br>\nг. Новосибирск, ул. Советская, 1А<br><br", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 82.922355, 55.01915, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Красном Яре (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=8101\"><img src=\"http:\/\/www.temples.ru\/private\/f000225\/225_0009465g.jpg\" border=1 width=\"180\" height=\"138\"><\/a><br><br>\nНовосибирская обл., Ордынский р-н, с", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 82.156407, 54.453727, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Собор Александра Невского (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=8029\"><img src=\"http:\/\/www.temples.ru\/private\/f000225\/225_0008908g.jpg\" border=1 width=\"120\" height=\"180\"><\/a><br><br>\nг. Новосибирск, ул. Советская, 1А<br><br", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 82.922648, 55.019458, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Покровский Александро-Невский Колыванский женский монастырь (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=8279\"><img src=\"http:\/\/www.temples.ru\/private\/f000225\/225_0009469g.jpg\" border=1 width=\"180\" height=\"119\"><\/a><br><br>\nНовосибирская обл., Колыванский р-н", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 82.73278, 55.299563, 0.0 ] } }
]
}
