var json__30 = {
"type": "FeatureCollection",
"name": "_30",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Григорово (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=13183\"><img src=\"http:\/\/www.temples.ru\/private\/f000306\/306_0045161g.jpg\" border=1 width=\"180\" height=\"124\"><\/a><br><br>\nг. Великий Новгород, просп. Алексан", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 31.220301, 58.549957, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Старой Руссе (не сохр.)", "descriptio": "\n<div align=\"center\">Новгородская обл., г. Старая Русса, [пл. Революции]<br><br><a href=\"http:\/\/www.temples.ru\/card.php?ID=13685\"><nobr><i>Подробная информация<\/i><\/nobr><\/a><br><br><\/div>", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 31.355646, 57.988977, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Демянске (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=17123\"><img src=\"http:\/\/www.temples.ru\/private\/f000101\/108_0113597g.jpg\" border=1 width=\"135\" height=\"180\"><\/a><br><br>\nНовгородская обл., Демянский р-н, п�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 32.46518, 57.64261, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Спасо-Преображенском Старорусском монастыре (не сохр.)", "descriptio": "\n<div align=\"center\">Новгородская обл., г. Старая Русса, ул. Володарского, [у д. 14]<br><br><a href=\"http:\/\/www.temples.ru\/card.php?ID=13485\"><nobr><i>Подробная информация<\/i><\/nobr><\/a><br><b", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 31.35991, 57.992912, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Валдае (не сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=18455\"><img src=\"http:\/\/www.temples.ru\/private\/f000101\/108_0131216g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nНовгородская обл., г. Валдай, Народ�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 33.25514, 57.97505, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Яжелбицах (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=17840\"><img src=\"http:\/\/www.temples.ru\/private\/f000209\/209_0126457g.jpg\" border=1 width=\"180\" height=\"119\"><\/a><br><br>\nНовгородская обл., Валдайский р-н, �", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 32.972217, 58.032279, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Иконы Божией Матери Коневская в Деревяницком монастыре (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=8236\"><img src=\"http:\/\/www.temples.ru\/private\/f000101\/108_0008964g.jpg\" border=1 width=\"180\" height=\"132\"><\/a><br><br>\nг. Великий Новгород, ул. Перспектив�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 31.300972, 58.562707, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Старой Руссе (не сохр.)", "descriptio": "\n<div align=\"center\">Новгородская обл., г. Старая Русса, наб. Штыкова<br><br><a href=\"http:\/\/www.temples.ru\/card.php?ID=13699\"><nobr><i>Подробная информация<\/i><\/nobr><\/a><br><br><\/div>", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 31.352867, 57.992543, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского при мужской гимназии (не сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=17423\"><img src=\"http:\/\/www.temples.ru\/private\/f000209\/209_0122876g.jpg\" border=1 width=\"180\" height=\"119\"><\/a><br><br>\nг. Новгород Великий, ул. Большая Мо�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 31.288962, 58.522252, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Селище (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=8460\"><img src=\"http:\/\/www.temples.ru\/private\/f000272\/272_0010818g.jpg\" border=1 width=\"180\" height=\"111\"><\/a><br><br>\nНовгородская обл., Валдайский р-н, д", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 33.530803, 57.834882, 0.0 ] } }
]
}
