var json__31 = {
"type": "FeatureCollection",
"name": "_31",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Ветлуге (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=9745\"><img src=\"http:\/\/www.temples.ru\/private\/f000264\/264_0087246g.jpg\" border=1 width=\"129\" height=\"180\"><\/a><br><br>\nНижегородская обл., Ветлужский р-н,", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 45.778434, 57.851379, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского (?) на Нижнем Базаре в Городце (не сохр.)", "descriptio": "\n<div align=\"center\">Нижегородская обл., Городецкий р-н, г. Городец, [Бол. Кировский съезд, напротив д. 22]<br><br><a href=\"http:\/\/www.temples.ru\/card.php?ID=18864\"><nobr><i>Подробная", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 43.464701, 56.645137, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского при 2-м детском приюте (не сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=14928\"><img src=\"http:\/\/www.temples.ru\/private\/f000518\/518_0082729g.jpg\" border=1 width=\"180\" height=\"146\"><\/a><br><br>\nг. Нижний Новгород, ул. Ульянова, 10<b", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 44.010093, 56.326281, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=3572\"><img src=\"http:\/\/www.temples.ru\/private\/f000742\/742_0142013g.jpg\" border=1 width=\"128\" height=\"180\"><\/a><br><br>\nг. Нижний Новгород, ул. Стрелка, д. 3а", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 43.971319, 56.333658, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Троицком Серафимо-Дивеевском монастыре (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=4408\"><img src=\"http:\/\/www.temples.ru\/private\/f000125\/125_0097458g.jpg\" border=1 width=\"180\" height=\"119\"><\/a><br><br>\nНижегородская обл., Дивеевский р-н,", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 43.246829, 55.039701, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Правдинске (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=9695\"><img src=\"http:\/\/www.temples.ru\/private\/f000340\/340_0019289g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nНижегородская обл., г. Балахна, мкрн", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 43.556503, 56.527258, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского при Александровском Дворянском институте (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=5911\"><img src=\"http:\/\/www.temples.ru\/private\/f000063\/067_0002687g.jpg\" border=1 width=\"180\" height=\"116\"><\/a><br><br>\nНижний Новгород, ул. Варварская, 3<br>", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 44.007969, 56.324819, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского при Александровской богадельне (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=19019\"><img src=\"http:\/\/www.temples.ru\/private\/f000518\/518_0140936g.jpg\" border=1 width=\"180\" height=\"126\"><\/a><br><br>\nг. Нижний Новгород, ул. Варварская,", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 44.014299, 56.319863, 0.0 ] } }
]
}
