var json__34 = {
"type": "FeatureCollection",
"name": "_34",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Ериловке (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=18270\"><img src=\"http:\/\/www.temples.ru\/private\/f000204\/204_0120450g.jpg\" border=1 width=\"180\" height=\"119\"><\/a><br><br>\nЛипецкая обл., Елецкий р-н, с. Ерило�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 38.770982, 52.689433, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Задонском Богородице-Тихоновском Тюнинском монастыре (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=14883\"><img src=\"http:\/\/www.temples.ru\/private\/f000204\/204_0122571g.jpg\" border=1 width=\"180\" height=\"110\"><\/a><br><br>\nЛипецкая обл., Задонский р-н, с. Тюн�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 38.92669, 52.415417, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского и Михаила Тверского в Ельце (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=17800\"><img src=\"http:\/\/www.temples.ru\/private\/f000204\/204_0121253g.jpg\" border=1 width=\"149\" height=\"180\"><\/a><br><br>\nЛипецкая обл., г. Елец, ул. Советска�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 38.499979, 52.62422, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского и Михаила Тверского в Ельце (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=17801\"><img src=\"http:\/\/www.temples.ru\/private\/f000204\/204_0121297g.jpg\" border=1 width=\"180\" height=\"119\"><\/a><br><br>\nЛипецкая обл., г. Елец, ул. Советска�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 38.500215, 52.624244, 0.0 ] } }
]
}
