var json__35 = {
"type": "FeatureCollection",
"name": "_35",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Часовня на Святой горе у Коневского монастыря (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=18203\"><img src=\"http:\/\/www.temples.ru\/private\/f000360\/360_0149400g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nЛенинградская обл., Приозерский р-�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 30.598659, 60.851856, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Арсения Коневского на Коневце (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=18206\"><img src=\"http:\/\/www.temples.ru\/private\/f000360\/360_0149558g.jpg\" border=1 width=\"151\" height=\"180\"><\/a><br><br>\nЛенинградская обл., Приозерский р-�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 30.596192, 60.857172, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Иконы Божией Матери Коневская в Коневском скиту Коневского монастыря (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=18205\"><img src=\"http:\/\/www.temples.ru\/private\/f000360\/360_0149047g.jpg\" border=1 width=\"180\" height=\"127\"><\/a><br><br>\nЛенинградская обл., Приозерский р-�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 30.603412, 60.839711, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня памятная в Невской Дубровке (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=15180\"><img src=\"http:\/\/www.temples.ru\/private\/f000577\/577_0088839g.jpg\" border=1 width=\"118\" height=\"180\"><\/a><br><br>\nЛенинградская обл., Всеволожский р", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 30.941416, 59.843166, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Собор Рождества Пресвятой Богородицы в Коневском монастыре (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=18196\"><img src=\"http:\/\/www.temples.ru\/private\/f000360\/360_0149917g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nЛенинградская обл., Приозерский р-�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 30.584165, 60.848187, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Успения Пресвятой Богородицы у Коневского монастыря (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=18200\"><img src=\"http:\/\/www.temples.ru\/private\/f000590\/590_0141920g.jpg\" border=1 width=\"135\" height=\"180\"><\/a><br><br>\nЛенинградская обл., Приозерский р-�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 30.589996, 60.849623, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Николая Чудотворца и Арсения Коневского в Большом Стремление (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=17486\"><img src=\"http:\/\/www.temples.ru\/private\/f000083\/087_0121750g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nЛенинградская обл., Кингисеппский", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 28.665825, 59.745914, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Николая Чудотворца у Коневского монастыря (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=18199\"><img src=\"http:\/\/www.temples.ru\/private\/f000360\/360_0149722g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nЛенинградская обл., Приозерский р-�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 30.579889, 60.847168, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Александровке (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=8680\"><img src=\"http:\/\/www.temples.ru\/private\/f000634\/634_0127869g.jpg\" border=1 width=\"180\" height=\"104\"><\/a><br><br>\nЛенинградская обл., Гатчинский р-н,", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 30.131472, 59.674203, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Иконы Божией Матери Взыскание Погибших в Невской Дубровке (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=15177\"><img src=\"http:\/\/www.temples.ru\/private\/f000577\/005_0088656g.jpg\" border=1 width=\"180\" height=\"180\"><\/a><br><br>\nЛенинградская обл., Всеволожский р", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 30.936792, 59.848216, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Коневский Рождество-Богородицкий мужской монастырь (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=18195\"><img src=\"http:\/\/www.temples.ru\/private\/f000715\/005_0131010g.jpg\" border=1 width=\"180\" height=\"101\"><\/a><br><br>\nЛенинградская обл., Приозерский р-�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 30.584272, 60.848075, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Арсения Коневского в Коневском монастыре (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=18198\"><img src=\"http:\/\/www.temples.ru\/private\/f000360\/360_0149774g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nЛенинградская обл., Приозерский р-�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 30.584809, 60.848858, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Николая Чудотворца в Коневском монастыре (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=18197\"><img src=\"http:\/\/www.temples.ru\/private\/f000360\/360_0149787g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nЛенинградская обл., Приозерский р-�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 30.58549, 60.847873, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Иконы Божией Матери Казанская в Казанском скиту Коневского монастыря (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=18202\"><img src=\"http:\/\/www.temples.ru\/private\/f000360\/360_0149507g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nЛенинградская обл., Приозерский р-�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 30.598423, 60.852093, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Казанский скит Коневского монастыря (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=18201\"><img src=\"http:\/\/www.temples.ru\/private\/f000360\/360_0149506g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nЛенинградская обл., Приозерский р-�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 30.598493, 60.852112, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Коневский скит Коневского монастыря (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=18204\"><img src=\"http:\/\/www.temples.ru\/private\/f000360\/360_0149066g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nЛенинградская обл., Приозерский р-�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 30.60345, 60.839589, 0.0 ] } }
]
}
