var json__40 = {
"type": "FeatureCollection",
"name": "_40",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского у Московских ворот (не сохр.)", "descriptio": "\n<div align=\"center\">г. Калуга, ул. Ленина<br><br><a href=\"http:\/\/www.temples.ru\/card.php?ID=12211\"><nobr><i>Подробная информация<\/i><\/nobr><\/a><br><br><\/div>", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 36.267953, 54.519449, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Высокиничах (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=11477\"><img src=\"http:\/\/www.temples.ru\/private\/f000430\/430_0075305g.jpg\" border=1 width=\"180\" height=\"119\"><\/a><br><br>\nКалужская обл., Жуковский р-н, с. Вы�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 36.916916, 54.909343, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского при Хлюстинских богоугодных заведениях (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=12174\"><img src=\"http:\/\/www.temples.ru\/private\/f000306\/306_0053621g.jpg\" border=1 width=\"180\" height=\"116\"><\/a><br><br>\nг. Калуга, ул. Никитина, 66<br><br><a href=\"ht", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 36.283406, 54.507598, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Кирове (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=13422\"><img src=\"http:\/\/www.temples.ru\/private\/f000306\/306_0062839g.jpg\" border=1 width=\"180\" height=\"120\"><\/a><br><br>\nКалужская обл., Кировский р-н, г. Ки�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 34.331296, 54.082849, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Собор Александра Невского в Жиздре (не сохр.)", "descriptio": "\n<div align=\"center\">Калужская обл., Жиздринский р-н, г. Жиздра, [перекресток ул. Коммунистическая и ул. Красноармейская]<br><br><a href=\"http:\/\/www.temples.ru\/card.php?ID=135", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 34.73479, 53.74797, 0.0 ] } }
]
}
