var json__43 = {
"type": "FeatureCollection",
"name": "_43",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского при реальном училище (не сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=7530\"><img src=\"http:\/\/www.temples.ru\/private\/f000002\/002_0006323g.jpg\" border=1 width=\"180\" height=\"109\"><\/a><br><br>\nг. Вологда, ул. Зосимовская, [1]<br><br><a", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 39.900906, 59.222394, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского и Марии Магдалины при детском приюте (не сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=7533\"><img src=\"http:\/\/www.temples.ru\/private\/f000002\/002_0006342g.jpg\" border=1 width=\"180\" height=\"122\"><\/a><br><br>\nг. Вологда, ул. Мальцева, [22]<br><br><a href=", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 39.877662, 59.22017, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=3212\"><img src=\"http:\/\/www.temples.ru\/private\/f000040\/vol-nevsk-1g.jpg\" border=1 width=\"120\" height=\"180\"><\/a><br><br>\nг. Вологда, ул. Сергея Орлова, 10<br><br><", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 39.884003, 59.224504, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в реальном училище (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=19725\"><img src=\"http:\/\/www.temples.ru\/private\/f000002\/002_0150589g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nВологодская обл., г. Череповец, про�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 37.921661, 59.12407, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Кичменгском Городке (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=15221\"><img src=\"http:\/\/www.temples.ru\/private\/f000264\/264_0085661g.jpg\" border=1 width=\"180\" height=\"177\"><\/a><br><br>\nВологодская обл., Кичменгско-Город", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 45.806635, 59.988685, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Григорьевском (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=7482\"><img src=\"http:\/\/www.temples.ru\/private\/f000002\/002_0006471g.jpg\" border=1 width=\"180\" height=\"138\"><\/a><br><br>\nг. Вологда, ул. Клубова, 63Б<br><br><a href=\"h", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 39.799272, 59.238792, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Ухтоме (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=7239\"><img src=\"http:\/\/www.temples.ru\/private\/f000212\/212_0005582g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nВологодская обл., Вашкинский р-н, с.", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 38.036664, 60.169829, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Заоникиевской Богородице-Владимирской пустыни (сохр.)", "descriptio": "\n<div align=\"center\">Вологодская обл., Вологодский р-н, д. Лучниково<br><br><a href=\"http:\/\/www.temples.ru\/card.php?ID=14957\"><nobr><i>Подробная информация<\/i><\/nobr><\/a><br><br><\/div>", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 39.836608, 59.342316, 0.0 ] } }
]
}
