var json__45 = {
"type": "FeatureCollection",
"name": "_45",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского на Михайловой Стороне (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=5395\"><img src=\"http:\/\/www.temples.ru\/private\/f000024\/025_0012733g.jpg\" border=1 width=\"180\" height=\"119\"><\/a><br><br>\nВладимирская обл., г. Суздаль, ул. Ми", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 40.460621, 56.4094, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Барсово (сохр.)", "descriptio": "\n<div align=\"center\">Владимирская обл., Киржачский р-н, пос. Барсово<br><br><a href=\"http:\/\/www.temples.ru\/card.php?ID=13216\"><nobr><i>Подробная информация<\/i><\/nobr><\/a><br><br><\/div>", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 38.773327, 56.109624, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Сингере (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=18214\"><img src=\"http:\/\/www.temples.ru\/private\/f000656\/656_0129218g.jpg\" border=1 width=\"120\" height=\"180\"><\/a><br><br>\nВладимирская обл., Вязниковский р-�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 42.040521, 56.273765, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского при мужской гимназии во Владимире (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=19584\"><img src=\"http:\/\/www.temples.ru\/private\/f000747\/747_0145989g.jpg\" border=1 width=\"135\" height=\"180\"><\/a><br><br>\nг. Владимир, ул. Большая Московская", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 40.408241, 56.129803, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь-часовня Александра Невского в Юрьевце (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=19589\"><img src=\"http:\/\/www.temples.ru\/private\/f000747\/747_0145716g.jpg\" border=1 width=\"135\" height=\"180\"><\/a><br><br>\nг. Владимир, мкрн. Юрьевец, ул. Нояб�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 40.274806, 56.099524, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Александрово (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=11608\"><img src=\"http:\/\/www.temples.ru\/private\/f000211\/211_0044674g.jpg\" border=1 width=\"180\" height=\"131\"><\/a><br><br>\nВладимирская обл., Суздальский р-н,", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 40.258175, 56.226053, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Рождественском Владимирском монастыре (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=5305\"><img src=\"http:\/\/www.temples.ru\/private\/f000204\/204_0115117g.jpg\" border=1 width=\"120\" height=\"180\"><\/a><br><br>\nг. Владимир, ул. Большая Московская,", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 40.414541, 56.130997, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Веси (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=10664\"><img src=\"http:\/\/www.temples.ru\/private\/f000372\/372_0024532g.jpg\" border=1 width=\"180\" height=\"119\"><\/a><br><br>\nВладимирская обл., Суздальский р-н,", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 40.36076, 56.48281, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Богоявленском Мстёрском монастыре (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=13909\"><img src=\"http:\/\/www.temples.ru\/private\/f000051\/055_0022322g.jpg\" border=1 width=\"135\" height=\"180\"><\/a><br><br>\nВладимирская обл., Вязниковский р-�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 41.939852, 56.374813, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Чамерово (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=17070\"><img src=\"http:\/\/www.temples.ru\/private\/f000264\/264_0115671g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nВладимирская обл., Судогодский р-н,", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 40.783561, 56.071842, 0.0 ] } }
]
}
