var json__49 = {
"type": "FeatureCollection",
"name": "_49",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Шелюбинской (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=14793\"><img src=\"http:\/\/www.temples.ru\/private\/f000264\/264_0080580g.jpg\" border=1 width=\"132\" height=\"180\"><\/a><br><br>\nАрхангельская обл., Вельский р-н, д.", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 41.891502, 61.010011, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Покрова Пресвятой Богородицы и Александра Невского в Конёво (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=10810\"><img src=\"http:\/\/www.temples.ru\/private\/f000215\/215_0027936g.jpg\" border=1 width=\"135\" height=\"180\"><\/a><br><br>\nАрхангельская обл., Плесецкий р-н, �", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 39.325803, 62.125519, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Северодвинске (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=4053\"><img src=\"http:\/\/www.temples.ru\/private\/f000090\/sev001g.jpg\" border=1 width=\"132\" height=\"180\"><\/a><br><br>\nАрхангельская обл., г. Северодвинск<br><", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 39.818412, 64.559928, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Шеговарах (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=14732\"><img src=\"http:\/\/www.temples.ru\/private\/f000264\/264_0081307g.jpg\" border=1 width=\"135\" height=\"180\"><\/a><br><br>\nАрхангельская обл., Шенкурский р-н,", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 42.954038, 62.379247, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Благовещенском (сохр.)", "descriptio": "\n<div align=\"center\">Архнагельская обл., Вельский р-н, с. Благовещенское<br><br><a href=\"http:\/\/www.temples.ru\/card.php?ID=18683\"><nobr><i>Подробная информация<\/i><\/nobr><\/a><br><br><\/div>", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 42.536037, 61.682977, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=3849\"><img src=\"http:\/\/www.temples.ru\/private\/f000264\/264_0078938g.jpg\" border=1 width=\"180\" height=\"139\"><\/a><br><br>\nАрхангельск<br><br><a href=\"http:\/\/www.temples.ru\/car", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 40.6643, 64.507478, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского Соловецкого монастыря (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=7665\"><img src=\"http:\/\/www.temples.ru\/private\/f000101\/108_0007366g.jpg\" border=1 width=\"135\" height=\"180\"><\/a><br><br>\nАрхангельская обл., Приморский р-н.,", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 35.707885, 65.024629, 0.0 ] } }
]
}
