var json__5 = {
"type": "FeatureCollection",
"name": "_5",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского при Тульской мужской гимназии (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=17810\"><img src=\"http:\/\/www.temples.ru\/private\/f000656\/656_0125584g.jpg\" border=1 width=\"180\" height=\"130\"><\/a><br><br>\nг. Тула, Менделеевская ул., 7<br><br><a hre", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 37.622016, 54.191694, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского при Тульской земской больнице (не сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=17807\"><img src=\"http:\/\/www.temples.ru\/private\/f000656\/656_0125582g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nг. Тула, наб. Дрейера, 14<br><br><a href=\"http:\/", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 37.61179, 54.204853, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Кирилла и Мефодия при Веневском духовном училище (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=1148\"><img src=\"http:\/\/www.temples.ru\/private\/f000101\/108_0030587g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nТульская обл., г. Венев, ул. Советска", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 38.27168, 54.35021, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=5559\"><img src=\"http:\/\/www.temples.ru\/private\/f000580\/580_0099942g.jpg\" border=1 width=\"180\" height=\"124\"><\/a><br><br>\nг. Тула, ул. Софьи Перовской, 5<br><br><a h", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 37.600107, 54.190723, 0.0 ] } }
]
}
