var json__50 = {
"type": "FeatureCollection",
"name": "_50",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Одинцовском Посаде (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=16364\"><img src=\"http:\/\/www.temples.ru\/private\/f000519\/519_0103233g.jpg\" border=1 width=\"117\" height=\"180\"><\/a><br><br>\nАлтайский край, г. Бийск, пос. Одинц", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 84.964222, 52.438519, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=8410\"><img src=\"http:\/\/www.temples.ru\/private\/f000225\/225_0010221g.jpg\" border=1 width=\"120\" height=\"180\"><\/a><br><br>\nг. Барнаул, пересечение просп. Лени�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 83.789651, 53.336175, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Собор Александра Невского (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=4448\"><img src=\"http:\/\/www.temples.ru\/private\/f000225\/225_0010117g.jpg\" border=1 width=\"180\" height=\"119\"><\/a><br><br>\nг. Барнаул, ул. Антона Петрова, 221<br><b", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 83.690393, 53.359414, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Славгороде (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=19081\"><img src=\"http:\/\/www.temples.ru\/private\/f000742\/005_0138841g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nАлтайский край, г. Славгород, Военн", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 78.63444, 52.995486, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня водосвятная при соборе Александра Невского (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=4450\"><img src=\"http:\/\/www.temples.ru\/private\/f000519\/519_0097435g.jpg\" border=1 width=\"119\" height=\"180\"><\/a><br><br>\nг. Барнаул, ул. Антона Петрова, 221<br><b", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 83.690484, 53.36016, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Собор Александра Невского в Бийске (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=15083\"><img src=\"http:\/\/www.temples.ru\/private\/f000519\/519_0085903g.jpg\" border=1 width=\"180\" height=\"119\"><\/a><br><br>\nАлтайский край, г. Бийск, ул. Красно", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 85.209789, 52.537004, 0.0 ] } }
]
}
