var json__7 = {
"type": "FeatureCollection",
"name": "_7",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=4381\"><img src=\"http:\/\/www.temples.ru\/private\/f000004\/004_0024297g.jpg\" border=1 width=\"122\" height=\"180\"><\/a><br><br>\nТверская обл., г. Старица<br><br><a href=\"htt", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 34.9303, 56.509525, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского на Мемориальном кладбище (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=11271\"><img src=\"http:\/\/www.temples.ru\/private\/f000004\/004_0039805g.jpg\" border=1 width=\"135\" height=\"180\"><\/a><br><br>\nТверская обл., г. Ржев, Осташковско�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 34.288169, 56.284731, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского и Александра Свирского при Духовном училище (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=14048\"><img src=\"http:\/\/www.temples.ru\/private\/f000204\/204_0071448g.jpg\" border=1 width=\"180\" height=\"119\"><\/a><br><br>\nТверская обл., г. Торжок, пл. Ананьи�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 34.956029, 57.041576, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Свердлове (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=1701\"><img src=\"http:\/\/www.temples.ru\/private\/f000004\/sverdlovo-1-1g.jpg\" border=1 width=\"140\" height=\"180\"><\/a><br><br>\nТверская обл., Конаковский р-н, с. С", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 36.613194, 56.632813, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Рамешках (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=4036\"><img src=\"http:\/\/www.temples.ru\/private\/f000002\/012-010g.jpg\" border=1 width=\"111\" height=\"180\"><\/a><br><br>\nТверская обл., Рамешковский р-н, пос. Р", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 36.044861, 57.345144, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского в Загорье (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=13669\"><img src=\"http:\/\/www.temples.ru\/private\/f000495\/495_0064267g.jpg\" border=1 width=\"180\" height=\"120\"><\/a><br><br>\nТверская обл., Торжокский р-н, д. За�", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 34.868398, 56.818998, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Синцове (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=1704\"><img src=\"http:\/\/www.temples.ru\/private\/f000002\/002_0019628g.jpg\" border=1 width=\"135\" height=\"180\"><\/a><br><br>\nТверская обл., Конаковский р-н, д. Си", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 36.065215, 56.428392, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Часовня Александра Невского в Западной Двине (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=16991\"><img src=\"http:\/\/www.temples.ru\/private\/f000264\/264_0114109g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nТверская обл., Западнодвинский р-н,", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 32.098833, 56.271264, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского у Бобачевской рощи (действ.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=17897\"><img src=\"http:\/\/www.temples.ru\/private\/f000656\/656_0127212g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nг. Тверь, ул. Склизкова, 102А<br><br><a href=", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 35.9375, 56.8314, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Церковь Александра Невского на Привокзальной площади (сохр.)", "descriptio": "\n<div align=\"center\"><a href=\"http:\/\/www.temples.ru\/gallery.php?CardID=17563\"><img src=\"http:\/\/www.temples.ru\/private\/f000779\/779_0154960g.jpg\" border=1 width=\"180\" height=\"135\"><\/a><br><br>\nг. Тверь, Привокзальная пл.<br><br><a href", "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ 35.893182, 56.836567, 0.0 ] } }
]
}
